name: brown_grow_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.14.2"

  # Firebase dependencies for authentication
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "lib/assets/logo1.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "lib/assets/logo1.png"
    web:
      generate: true
      image_path: "lib/assets/logo1.png"
      background_color: "#hexcode"
      theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "lib/assets/logo1.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "lib/assets/logo1.png"

flutter:
  uses-material-design: true